pvmfw_avb: Derive Eq for VerifiedBootData
Derive the trait, which can be used in tests assert_eq! and fill force a
programmer adding a new field to the structure to cover it in tests:

    error[E0063]: missing field `X` in initializer of `pvmfw_avb::VerifiedBootData<'_>`

On mismatch, assert_eq prints out the debug representation of the inputs:

    STACKTRACE:
    ---- TEST_NAME stderr ----
    thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `VerifiedBootData { debug_level: None, kernel_digest: [...], initrd_digest: None, }`,
    right: `VerifiedBootData { debug_level: None, kernel_digest: [...], initrd_digest: Some([...]) }`,
    packages/modules/Virtualization/pvmfw/avb/tests/api_test.rs:71:5

Note: no functional change intended.

Test: atest libpvmfw_avb.integration_test
Change-Id: Ia9b7046ff24ebffe6d15a6cc936a3ac2e8a5d4b9