Move test module below implementation details
```
error: items after a test module
    -->
packages/modules/Virtualization/virtualizationmanager/src/aidl.rs:1414:1
     |
1414 | mod tests {
     | ^^^^^^^^^
...
1630 | struct SecretkeeperProxy(Strong<dyn ISecretkeeper>);
     | ^^^^^^^^^^^^^^^^^^^^^^^^
1631 |
1632 | impl Interface for SecretkeeperProxy {}
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1633 |
1634 | impl ISecretkeeper for SecretkeeperProxy {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
1654 | struct AuthGraphKeyExchangeProxy(Strong<dyn IAuthGraphKeyExchange>);
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1655 |
1656 | impl Interface for AuthGraphKeyExchangeProxy {}
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1657 |
1658 | impl IAuthGraphKeyExchange for AuthGraphKeyExchangeProxy {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = help: for further information visit
https://rust-lang.github.io/rust-clippy/master/index.html#items_after_test_module
     = note: `-D clippy::items-after-test-module` implied by `-D
warnings`
     = help: to override `-D warnings` add
`#[allow(clippy::items_after_test_module)]`
     = help: move the items to before the test module was defined
```

Bug: http://b/321303117
Test: toolchain/android_rust/test_compiler.py --prebuilt-path dist/rust-dev.tar.xz --target aosp_cf_x86_64_phone --all-rust
Change-Id: I5d7fde0a147df087c5d99c1bf4a81177b662fe60